---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8001}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[provtest::webnode]
      - recipe[provtest::appnode]
    attributes:
